package com.nori.simple;
import android.Manifest;import android.app.Activity;import android.content.Intent;import android.content.pm.PackageManager;import android.os.Bundle;import android.speech.RecognitionListener;import android.speech.RecognizerIntent;import android.speech.SpeechRecognizer;import android.speech.tts.TextToSpeech;import android.webkit.*;import androidx.annotation.Nullable;import androidx.webkit.WebViewAssetLoader;import java.util.ArrayList;import java.util.Locale;
public class MainActivity extends Activity{private WebView webView;private WebViewAssetLoader loader;private SpeechRecognizer recognizer;private TextToSpeech tts;
@Override public void onCreate(@Nullable Bundle s){super.onCreate(s);webView=new WebView(this);setContentView(webView);webView.getSettings().setJavaScriptEnabled(true);webView.getSettings().setDomStorageEnabled(true);webView.getSettings().setMediaPlaybackRequiresUserGesture(false);loader=new WebViewAssetLoader.Builder().addPathHandler("/assets/",new WebViewAssetLoader.AssetsPathHandler(this)).build();webView.setWebViewClient(new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return loader.shouldInterceptRequest(r.getUrl());}});webView.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(final PermissionRequest r){runOnUiThread(()->{if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)r.grant(r.getResources());else r.deny();});}});webView.addJavascriptInterface(new Bridge(),"NoriNative");tts=new TextToSpeech(this,status->{if(status==TextToSpeech.SUCCESS)tts.setLanguage(Locale.getDefault());});if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},7);webView.loadUrl("https://appassets.androidplatform.net/assets/index.html");}
private class Bridge{@JavascriptInterface public void startListening(){runOnUiThread(()->{if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},7);return;}if(recognizer==null)recognizer=SpeechRecognizer.createSpeechRecognizer(MainActivity.this);recognizer.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle p){}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){js("window.__noriNativeVoiceError&&window.__noriNativeVoiceError("+e+")");}public void onResults(Bundle b){ArrayList<String>a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(a!=null&&!a.isEmpty())js("window.__noriNativeText&&window.__noriNativeText("+quote(a.get(0))+")");js("window.__noriNativeVoiceDone&&window.__noriNativeVoiceDone()");}public void onPartialResults(Bundle b){}public void onEvent(int t,Bundle p){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,Locale.getDefault());i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,false);recognizer.startListening(i);});}
@JavascriptInterface public void stopListening(){runOnUiThread(()->{if(recognizer!=null)try{recognizer.stopListening();}catch(Exception ignored){}});}
@JavascriptInterface public void speak(String text){runOnUiThread(()->{if(tts!=null){tts.stop();tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,"nori");}});}
@JavascriptInterface public void stopSpeaking(){runOnUiThread(()->{if(tts!=null)tts.stop();});}}
private void js(String s){runOnUiThread(()->webView.evaluateJavascript(s,null));}private String quote(String s){return "\""+s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r")+"\"";}
@Override protected void onDestroy(){if(recognizer!=null)recognizer.destroy();if(tts!=null)tts.shutdown();if(webView!=null)webView.destroy();super.onDestroy();}}
